name: bottom_bar_matu_example

description: Demonstrates how to use the bottom_bar_matu packageg.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  bottom_bar_matu:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/

